/**
 * Build the semantic PR summary comment from SAFE public intent views
 * (ADR-009). Never receives or renders `prompt` — the full prompt is private
 * and must never appear in a PR comment or check-run summary.
 */

import { sanitizePublicText } from "@drift/core";
import type { IntentView } from "./intents.js";

/**
 * Invisible marker embedded in every Drift summary comment. The webhook
 * handler uses it to find an existing comment and update it in place, so
 * comments never accumulate across `synchronize` deliveries.
 */
export const SUMMARY_MARKER = "<!-- drift:summary -->";

export interface SummaryInput {
  owner: string;
  repo: string;
  prNumber: number;
  prTitle: string;
  intents: IntentView[];
  repoUrl?: string;
}

/** Hard caps so a pathological PR can never produce a huge comment. */
const MAX_INTENTS = 10;
const MAX_FILES = 10;
const SUMMARY_LIMIT = 500;
const META_LIMIT = 120;

/** Sanitize + clamp a value for public rendering. */
function safe(text: string | null | undefined, limit: number): string {
  const cleaned = sanitizePublicText(String(text ?? "")).replace(/`/g, "");
  return cleaned.length <= limit ? cleaned : `${cleaned.slice(0, limit - 1)}…`;
}

/** Human label for a manifest signature/trust state (never the raw prompt). */
const SIGNATURE_LABELS: Record<string, string> = {
  valid: "✓ signed (trusted repository key)",
  invalid: "⚠ invalid signature",
  unsigned: "no signature",
  unverifiable: "⚠ unverifiable (no verification key)",
  "untrusted-key": "⚠ unverified — signed with a different key than the base branch",
  bootstrap: "unverified bootstrap (base branch has no Drift key yet)",
  missing: "⚠ public provenance manifest missing",
};

export function summarizeIntents(input: SummaryInput): string {
  const intents = input.intents.slice(0, MAX_INTENTS);
  const truncated = input.intents.length > MAX_INTENTS;
  const lines: string[] = [];

  lines.push(SUMMARY_MARKER);
  lines.push("## Drift — Why this changed");
  lines.push("");
  lines.push(`${intents.length} intent${intents.length === 1 ? "" : "s"} on this PR · ${input.prTitle ? safe(input.prTitle, 80) : ""}`);

  for (const intent of intents) {
    lines.push("");
    lines.push(`### Intent \`${safe(intent.id, 12)}\``);
    lines.push("");
    if (intent.missingManifest) {
      lines.push("_(public provenance manifest missing — summary is a generic fallback)_");
    } else {
      lines.push(safe(intent.summary, SUMMARY_LIMIT) || "_(no public summary recorded)_");
    }
    const trust = SIGNATURE_LABELS[intent.signatureState];
    if (trust) {
      lines.push("");
      lines.push(`_${trust}_`);
    }

    const meta: string[] = [];
    if (intent.authorId) meta.push(safe(intent.authorId, META_LIMIT));
    if (intent.authorType && intent.authorType !== "unknown") meta.push(`(${safe(intent.authorType, 16)})`);
    if (intent.model) meta.push(`model ${safe(intent.model, META_LIMIT)}`);
    if (meta.length > 0) {
      lines.push("");
      lines.push("### Generated with");
      lines.push("");
      lines.push(meta.join(" · "));
    }

    if (intent.files.length > 0) {
      lines.push("");
      lines.push("### Affected code");
      lines.push("");
      for (const f of intent.files.slice(0, MAX_FILES)) {
        const detail = f.summary ? ` — ${safe(f.summary, 90)}` : "";
        lines.push(`- \`${safe(f.path, 200)}\` (**${safe(f.mutationType, 16)}**)${detail}`);
      }
      if (intent.files.length > MAX_FILES) lines.push(`- … +${intent.files.length - MAX_FILES} more`);
    }

    if (intent.verifyCmd) {
      lines.push("");
      lines.push("### Verification");
      lines.push("");
      lines.push(`- \`${safe(intent.verifyCmd, META_LIMIT)}\``);
    }

    lines.push("");
    lines.push("### Trace");
    lines.push("");
    lines.push(`- Intent: ${safe(intent.id, 40)}`);
  }

  if (truncated) {
    lines.push("");
    lines.push(`_… and ${input.intents.length - MAX_INTENTS} more intent(s) not shown._`);
  }

  lines.push("");
  lines.push("---");
  lines.push("_Generated by [Drift](https://github.com/lilcipherx/drift) — Git tracks what changed. Drift tracks why._");
  return lines.join("\n");
}
