/**
 * Build the semantic PR summary comment from intents (PRD §16.2, §26.3):
 * "Review intent, not 2,000 lines of diff."
 */

import type { IntentView } from "./intents.js";

/**
 * Invisible marker embedded in every Drift summary comment. The webhook
 * handler uses it to find an existing comment and update it in place, so
 * comments never accumulate across `synchronize` deliveries.
 */
export const SUMMARY_MARKER = "<!-- drift:summary -->";

export interface SummaryInput {
  owner: string;
  repo: string;
  prNumber: number;
  prTitle: string;
  intents: IntentView[];
  repoUrl?: string;
}

const TRUNCATE = 140;

function truncate(text: string): string {
  if (text.length <= TRUNCATE) return text;
  return `${text.slice(0, TRUNCATE - 1)}…`;
}

/** Escape `|` so untrusted paths/summaries cannot break the markdown table. */
function escCell(text: string | null | undefined): string {
  return String(text ?? "").replace(/\|/g, "\\|");
}

export function summarizeIntents(input: SummaryInput): string {
  const { intents } = input;
  const authors = new Set(intents.map((i) => `${i.authorId} (${i.authorType})`));
  const lines: string[] = [];

  lines.push(SUMMARY_MARKER);
  lines.push(`## 🤖 Drift intent summary`);
  lines.push("");
  lines.push(
    `${intents.length} intent${intents.length === 1 ? "" : "s"} on this PR · ` +
      `${authors.size} author${authors.size === 1 ? "" : "s"}` +
      (input.repoUrl ? ` · [open in Drift](${input.repoUrl})` : ""),
  );

  for (const intent of intents) {
    lines.push("");
    lines.push(`### Intent \`${intent.id.slice(0, 8)}…\``);
    lines.push("");
    const meta = [
      `**Author:** \`${intent.authorId}\` (${intent.authorType})`,
      intent.model ? `**Model:** \`${intent.model}\`` : null,
      intent.signature ? "**Signature:** ✍ Ed25519" : null,
      intent.encryptedPrompt ? "**Prompt:** 🔒 encrypted" : null,
    ].filter(Boolean);
    if (meta.length) lines.push(meta.join(" · "));
    lines.push("");
    lines.push(`> ${truncate(intent.prompt || "_(no prompt recorded)_")}`);

    if (intent.files.length > 0) {
      lines.push("");
      lines.push("| File | Change |");
      lines.push("| --- | --- |");
      for (const f of intent.files.slice(0, 12)) {
        lines.push(`| \`${escCell(f.path)}\` | **${f.mutationType}** — ${escCell(f.summary) || "changed"} |`);
      }
      if (intent.files.length > 12) {
        lines.push(`| … | +${intent.files.length - 12} more |`);
      }
    } else {
      lines.push("");
      lines.push("_No semantic delta recorded (intent object not found — was `.drift/` committed?)._");
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("_Generated by [Drift](https://github.com/lilcipherx/drift) — Git tracks what changed. Drift tracks why._");
  return lines.join("\n");
}
