#!/usr/bin/env node
/**
 * Drift PR summary comment (GitHub Action).
 *
 * Runs `drift log --json` in the consumer repository and posts (or updates
 * in place — idempotent, marker-based) a compact provenance summary on the
 * pull request. Zero extra dependencies: plain `fetch` + the REST API.
 *
 * Env:
 *   GITHUB_TOKEN       token for the API (from `${{ github.token }}`)
 *   GITHUB_REPOSITORY  owner/repo of the run
 *   GITHUB_EVENT_PATH  event JSON file (pull_request.number)
 *   DRIFT_CLI          path to the drift CLI (default: packages/drift-cli/dist/cli.js)
 *
 * Graceful behaviour: skips silently when the run is not a pull_request,
 * when the repo has no Drift intents, or when Drift is not initialized.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";

export const SUMMARY_MARKER = "<!-- drift:summary -->";
const PROMPT_TRUNCATE = 200;
const MAX_FILES = 10;

function escCell(text) {
  return String(text ?? "").replace(/\|/g, "\\|");
}

function truncate(text) {
  const s = String(text ?? "");
  return s.length <= PROMPT_TRUNCATE ? s : `${s.slice(0, PROMPT_TRUNCATE - 1)}…`;
}

/** Build the summary comment body. Returns null when there is nothing to say. */
export function buildSummary(intents) {
  if (!Array.isArray(intents) || intents.length === 0) return null;
  const lines = [SUMMARY_MARKER, "## 🤖 Drift intent summary", ""];
  lines.push(`${intents.length} intent${intents.length === 1 ? "" : "s"} on this PR`);
  for (const intent of intents) {
    lines.push("", `### Intent \`${String(intent.id ?? "?").slice(0, 8)}…\``, "");
    const meta = [`**Author:** \`${escCell(intent.authorId ?? "unknown")}\` (${escCell(intent.authorType ?? "unknown")})`];
    if (intent.model) meta.push(`**Model:** \`${escCell(intent.model)}\``);
    if (intent.gitSha) meta.push(`**Commit:** \`${String(intent.gitSha).slice(0, 7)}\``);
    lines.push(meta.join(" · "), "");
    lines.push(`> ${truncate(intent.prompt) || "_(no prompt recorded)_"}`);
    const files = Array.isArray(intent.files) ? intent.files : [];
    if (files.length > 0) {
      lines.push("", "| File | Change |", "| --- | --- |");
      for (const f of files.slice(0, MAX_FILES)) {
        lines.push(`| \`${escCell(f.path)}\` | **${escCell(f.mutationType)}** |`);
      }
      if (files.length > MAX_FILES) lines.push(`| … | +${files.length - MAX_FILES} more |`);
    }
  }
  lines.push(
    "",
    "---",
    "_Generated by [Drift](https://github.com/lilcipherx/drift) — Git tracks what changed. Drift tracks why._",
  );
  return lines.join("\n");
}

/**
 * Post the comment, or update the existing Drift comment in place
 * (idempotent across `synchronize` deliveries and force-pushes).
 */
export async function upsertComment({ token, repo, issueNumber, body, fetchImpl = fetch }) {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "drift-action",
  };
  const list = await fetchImpl(`https://api.github.com/repos/${repo}/issues/${issueNumber}/comments?per_page=100`, { headers });
  if (!list.ok) throw new Error(`list comments: HTTP ${list.status}`);
  const comments = (await list.json()) ?? [];
  const existing = Array.isArray(comments)
    ? comments.find((c) => typeof c?.body === "string" && c.body.includes(SUMMARY_MARKER))
    : undefined;
  if (existing) {
    const res = await fetchImpl(`https://api.github.com/repos/${repo}/issues/comments/${existing.id}`, {
      method: "PATCH",
      headers,
      body: JSON.stringify({ body }),
    });
    if (!res.ok) throw new Error(`update comment: HTTP ${res.status}`);
    return { action: "updated", id: existing.id };
  }
  const res = await fetchImpl(`https://api.github.com/repos/${repo}/issues/${issueNumber}/comments`, {
    method: "POST",
    headers,
    body: JSON.stringify({ body }),
  });
  if (!res.ok) throw new Error(`post comment: HTTP ${res.status}`);
  return { action: "commented", id: (await res.json()).id };
}

async function main() {
  // Only pull_request events carry a PR number worth commenting on.
  let prNumber = null;
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (eventPath && existsSync(eventPath)) {
    try {
      prNumber = JSON.parse(readFileSync(eventPath, "utf8"))?.pull_request?.number ?? null;
    } catch {
      /* malformed event file — treat as no PR */
    }
  }
  const repo = process.env.GITHUB_REPOSITORY ?? "";
  const token = process.env.GITHUB_TOKEN ?? "";
  if (!prNumber || !repo) {
    console.log("pr-comment: not a pull-request run — skipping");
    return;
  }
  if (!token) {
    console.log("pr-comment: GITHUB_TOKEN not set — skipping comment (CI check still ran)");
    return;
  }

  const cli = process.env.DRIFT_CLI || "packages/drift-cli/dist/cli.js";
  const res = spawnSync(process.execPath, [cli, "log", "--json", "--limit", "20"], {
    cwd: process.cwd(),
    encoding: "utf8",
    env: { ...process.env, NO_COLOR: "1" },
    windowsHide: true,
  });
  if (res.status !== 0) {
    const msg = (res.stderr || res.stdout || "drift log failed").trim();
    // A repo that never initialized Drift has nothing to summarize — that is
    // expected, not an error.
    if (/Not a Drift repository/.test(msg)) {
      console.log("pr-comment: no Drift intents in this repository — skipping");
      return;
    }
    console.error(`pr-comment: drift log failed: ${msg}`);
    process.exitCode = 1;
    return;
  }
  let parsed;
  try {
    parsed = JSON.parse(res.stdout);
  } catch {
    console.error("pr-comment: drift log produced no JSON output");
    process.exitCode = 1;
    return;
  }
  const body = buildSummary(parsed?.intents ?? []);
  if (!body) {
    console.log("pr-comment: no intents on this PR — skipping comment");
    return;
  }
  try {
    const result = await upsertComment({ token, repo, issueNumber: prNumber, body });
    console.log(`pr-comment: ${result.action} comment #${result.id}`);
  } catch (err) {
    console.error(`pr-comment: failed to ${err instanceof Error ? err.message : String(err)}`);
    process.exitCode = 1;
  }
}

// Run only when executed as a script, not when imported by tests.
const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href;
if (isMain) main();
